QUEUED = 'QUEUED'
ASSIGNED = 'ASSIGNED'
RUNNING = 'RUNNING'

COMPLETED = 'COMPLETED'
FAILED = 'FAILED'
TIMEOUT = 'TIMEOUT'
STOPPED = 'STOPPED'

ACTIVE = 'ACTIVE'
TERMINATE = 'TERMINATE'
DISABLED = 'DISABLED'
KILL = 'KILL'
PICK = 'PICK'
STOP_TASK = 'STOP_TASK'
EXPIRED = 'EXPIRED'

# SECONDS = 1
# HEARTBEAT = 3 * SECONDS
# MAXHIBERNATION = 10
# CLEAROUT = '!clear!'
# RESULTINFILE = 'result_in_file:'

TASK_STATUS = (QUEUED, RUNNING, COMPLETED, FAILED, TIMEOUT, STOPPED, EXPIRED,)
RUN_STATUS = (RUNNING, COMPLETED, FAILED, TIMEOUT, STOPPED,)
WORKER_STATUS = (ACTIVE, PICK, DISABLED, TERMINATE, KILL, STOP_TASK,)

SECONDS = 1
CYCLES = 10
HEARTBEAT = CYCLES * SECONDS